-- MySQL Script generated by MySQL Workbench
-- Wed Mar 18 12:03:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Universidad` DEFAULT CHARACTER SET utf8 ;
USE `Universidad` ;

-- -----------------------------------------------------
-- Table `Universidad`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Universidad`.`cursos` ;

CREATE TABLE IF NOT EXISTS `Universidad`.`cursos` (
  `idCurso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreDescriptivo` VARCHAR(55) NOT NULL,
  `nAsignatura` INT NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidad`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Universidad`.`profesores` ;

CREATE TABLE IF NOT EXISTS `Universidad`.`profesores` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(55) NOT NULL,
  `apellidos` VARCHAR(55) NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProfesor`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Universidad`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Universidad`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `Universidad`.`alumnos` (
  `idAlumno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nif` VARCHAR(40) NOT NULL,
  `nombre` VARCHAR(55) NOT NULL,
  `apellidos` VARCHAR(55) NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `beca` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAlumno`),
  UNIQUE INDEX `idAlumno_UNIQUE` (`idAlumno` ASC) VISIBLE,
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
